default_platform(:ios)

platform :ios do
  desc "CI: build and upload to TestFlight"
  lane :ci_beta do
    # Temporary keychain on runner
    create_keychain(
      name: "ci_keychain",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    # App Store Connect API key
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_API_KEY_P8"],
      is_key_content_base64: false,
      in_house: false
    )

    # Certificates & profiles in your private repo
    match(
      type: "appstore",
      readonly: false,
      git_url: ENV["MATCH_GIT_URL"],
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
      storage_mode: "git",
      app_identifier: [ENV["APP_IDENTIFIER"]],
      keychain_name: "ci_keychain",
      keychain_password: "",
      verbose: true
    )

    # IMPORTANT: Xcode workspace generated by Expo prebuild is at root/ios
    scheme_name = ENV.fetch("IOS_SCHEME", "VisionGram")
    build_ios_app(
      workspace: Dir["ios/*.xcworkspace"].first,
      scheme: scheme_name,
      configuration: "Release",
      export_method: "app-store",
      clean: true
    )

    upload_to_app_store(
      api_key: api_key,
      skip_screenshots: true,
      skip_metadata: true,
      reject_if_possible: false,
      submit_for_review: false
    )
  ensure
    delete_keychain(name: "ci_keychain") rescue nil
  end
end
