default_platform(:ios)

platform :ios do
  desc "CI: build and upload to TestFlight"
  lane :ci_beta do
    create_keychain(
      name: "ci_keychain",
      password: "ci_keychain",

      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_API_KEY_P8"],
      is_key_content_base64: false,
      in_house: false
    )

    automatic_code_signing(
  use_automatic_signing: true,        
path: 'ios/VisionGram.xcodeproj',
  

      team_id: ENV["TEAM_ID"]
    )



    # build INSIDE ios/
    Dir.chdir("ios") do
      xcworkspace = Dir["*.xcworkspace"].first
      UI.user_error!("No .xcworkspace found in ios/") unless xcworkspace

      scheme_name = ENV["IOS_SCHEME"] || "VisionGram"

      build_ios_app(
      workspace: xcworkspace,
      scheme: scheme_name,
      configuration: "Release",
      export_method: "app-store",
      clean: true,
      xcargs: "-allowProvisioningUpdates"
    )
end

    upload_to_app_store(
      api_key: api_key,
      skip_screenshots: true,
      skip_metadata: true,
      reject_if_possible: false,
      submit_for_review: false
    )
  ensure
    delete_keychain(name: "ci_keychain") rescue nil
  end
end
