name: iOS TestFlight (stable)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ruby toolchain for fastlane/cocoapods
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Install Fastlane & CocoaPods (pinned)
        run: |
          gem install fastlane -N
          gem install cocoapods -v 1.14.3 -N
          fastlane --version
          pod --version

      # Node for RN/Expo bundling
      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Import distribution .p12 and App Store .mobileprovision
      - name: Import distribution cert & profile into CI keychain
        shell: bash
        env:
          CI_KEYCHAIN_PW:      ${{ secrets.CI_KEYCHAIN_PW }}
          DIST_P12_BASE64:     ${{ secrets.DIST_P12_BASE64 }}
          DIST_P12_PASSWORD:   ${{ secrets.DIST_P12_PASSWORD }}
          DIST_PROFILE_BASE64: ${{ secrets.DIST_PROFILE_BASE64 }}
        run: |
          set -euo pipefail
          KEYCHAIN="$HOME/Library/Keychains/ci_keychain-db"

          # Import .p12 (certificate + private key)
          echo "$DIST_P12_BASE64" | base64 -d > dist.p12
          security import dist.p12 -k "$KEYCHAIN" -P "$DIST_P12_PASSWORD" \
            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild -T /usr/bin/productsign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$CI_KEYCHAIN_PW" "$KEYCHAIN"

          # Decode + parse the provisioning profile
          echo "$DIST_PROFILE_BASE64" | base64 -d > dist.mobileprovision
          PROFILE_XML=$(/usr/bin/security cms -D -i dist.mobileprovision | plutil -convert xml1 -o - -)
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< "$PROFILE_XML")
          PROFILE_NAME=$(/usr/libexec/PlistBuddy -c 'Print :Name' /dev/stdin <<< "$PROFILE_XML" | tr -d '\r')
          APP_ID=$(/usr/libexec/PlistBuddy -c 'Print :Entitlements:application-identifier' /dev/stdin <<< "$PROFILE_XML" | tr -d '\r')

          echo "Profile Name: $PROFILE_NAME"
          echo "Profile UUID: $PROFILE_UUID"
          echo "Profile AppID: $APP_ID"

          # Install profile where Xcode expects it
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          cp dist.mobileprovision "$HOME/Library/MobileDevice/Provisioning Profiles/${PROFILE_UUID}.mobileprovision"

          # Expose for later steps
          echo "PROFILE_NAME=$PROFILE_NAME" >> "$GITHUB_ENV"
          echo "PROFILE_UUID=$PROFILE_UUID" >> "$GITHUB_ENV"

      - name: Show discovered profile name
        run: echo "PROFILE_NAME=$PROFILE_NAME / UUID=$PROFILE_UUID"

      # Preflight: App target (Release) settings
      - name: Show Xcode app Release build settings (preflight)
        run: |
          xcodebuild -showBuildSettings \
            -workspace ios/VisionGram.xcworkspace \
            -scheme VisionGram \
            -configuration Release 2>/dev/null | \
            egrep 'PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|CODE_SIGN_STYLE|CODE_SIGN_IDENTITY|PROVISIONING_PROFILE_SPECIFIER' || true

      # Preflight: Pods aggregate target (helps confirm pods are not forced to sign)
      - name: Show Pods aggregate Release build settings (preflight)
        run: |
          if [ -f ios/Pods/Pods.xcodeproj/project.pbxproj ]; then
            xcodebuild -showBuildSettings \
              -project ios/Pods/Pods.xcodeproj \
              -scheme "Pods-VisionGram" \
              -configuration Release 2>/dev/null | \
              egrep 'CODE_SIGN_STYLE|PROVISIONING_PROFILE_SPECIFIER|DEVELOPMENT_TEAM' || true
          fi

      # Build & upload with Fastlane
      - name: Fastlane (build & upload to TestFlight)
        env:
          # App / Team / Scheme
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}   # e.g. com.visiongram.app
          TEAM_ID:        ${{ secrets.TEAM_ID }}          # 10-char Apple Team ID
          IOS_SCHEME:     ${{ vars.IOS_SCHEME }}          # optional; defaults to VisionGram

          # App Store Connect API key (Fastfile reads these)
          ASC_KEY_ID:     ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID:  ${{ secrets.ASC_ISSUER_ID }}
          ASC_API_KEY_P8: ${{ secrets.ASC_API_KEY_P8 }}

          # Keychain password used by the lane
          CI_KEYCHAIN_PW: ${{ secrets.CI_KEYCHAIN_PW }}

          # Import step output
          PROFILE_NAME:   ${{ env.PROFILE_NAME }}
          PROFILE_UUID:   ${{ env.PROFILE_UUID }}
        run: fastlane ios ci_beta

      - name: Show gym log tail (debug)
        if: always()
        run: tail -n 500 ~/Library/Logs/gym/VisionGram-VisionGram.log || true

      - name: Upload gym logs (artifact)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gym-logs
          path: ~/Library/Logs/gym/
