name: iOS TestFlight (stable)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ruby toolchain (fastlane/cocoapods via gems)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Install Fastlane & CocoaPods (pinned)
        run: |
          gem install fastlane -N
          gem install cocoapods -v 1.14.3 -N
          fastlane --version
          pod --version

      # Node for Expo prebuild fallback in Fastfile
      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Import your Distribution .p12 + App Store profile and expose PROFILE_NAME
      - name: Import distribution cert & profile into CI keychain
        shell: bash
        env:
          CI_KEYCHAIN_PW: ${{ secrets.CI_KEYCHAIN_PW }}
          DIST_P12_BASE64: ${{ secrets.DIST_P12_BASE64 }}
          DIST_P12_PASSWORD: ${{ secrets.DIST_P12_PASSWORD }}
          DIST_PROFILE_BASE64: ${{ secrets.DIST_PROFILE_BASE64 }}
        run: |
          set -euo pipefail
          KEYCHAIN="$HOME/Library/Keychains/ci_keychain-db"

       # Import .p12 (certificate + private key)
         echo "$DIST_P12_BASE64" | base64 -d > dist.p12
          security import dist.p12 -k "$KEYCHAIN" -P "$DIST_P12_PASSWORD" \
          -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild -T /usr/bin/productsign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$CI_KEYCHAIN_PW" "$KEYCHAIN"

    # Install provisioning profile
        echo "$DIST_PROFILE_BASE64" | base64 -d > dist.mobileprovision
        PROFILE_XML=$(/usr/bin/security cms -D -i dist.mobileprovision | plutil -convert xml1 -o - -)
        PROFILE_UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< "$PROFILE_XML")
        PROFILE_NAME=$(/usr/libexec/PlistBuddy -c 'Print :Name' /dev/stdin <<< "$PROFILE_XML" | tr -d '\r')

        mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
        cp dist.mobileprovision "$HOME/Library/MobileDevice/Provisioning Profiles/$PROFILE_UUID.mobileprovision"

    # Persist to next steps (this is the critical line)
    printf 'PROFILE_NAME=%s\n' "$PROFILE_NAME" >> "$GITHUB_ENV"

      - name: Show discovered profile name
        run: echo "PROFILE_NAME=$PROFILE_NAME"

      - name: Show discovered profile name
        run: echo "PROFILE_NAME=$PROFILE_NAME"

      # Build & upload with Fastlane (uses Fastfile lane :ci_beta)
      
      - name: Fastlane (build & upload to TestFlight)
        env:
          # App / team / scheme
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}     # e.g. com.visiongram.app
          TEAM_ID:        ${{ secrets.TEAM_ID }}            # your 10-char Apple team id
          IOS_SCHEME:     ${{ vars.IOS_SCHEME }}            # optional; default is VisionGram

          # App Store Connect API key (used by Fastfile)
          ASC_KEY_ID:       ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID:    ${{ secrets.ASC_ISSUER_ID }}
          ASC_API_KEY_P8:   ${{ secrets.ASC_API_KEY_P8 }}

          # CI keychain password (same one you set as a secret)
          CI_KEYCHAIN_PW: ${{ secrets.CI_KEYCHAIN_PW }}

          # Optional (if your Appfile references it)
          APPLE_ID: ${{ secrets.APPLE_ID }}
        run: fastlane ios ci_beta
