name: iOS TestFlight (fixed)

on:
  workflow_dispatch:

jobs:
  build-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Expo login (EXPO_TOKEN)
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Write asc_key.p8 from secret
        env:
          ASC_JSON: ${{ secrets.APP_STORE_CONNECT_API_KEY_JSON }}
        run: |
          node -e "const fs=require('fs');const j=JSON.parse(process.env.ASC_JSON);fs.writeFileSync('asc_key.p8', j.key);"

      - name: Ensure eas.json for EAS Submit
        run: |
          cat > eas.json <<'JSON'
          {
            "submit": {
              "production": {
                "ios": {
                  "ascApiKeyPath": "./asc_key.p8",
                  "ascApiKeyIssuerId": "05448018-fd93-49f6-8700-e8c51d49b5c6",
                  "ascApiKeyId": "HJ5S2PTMX4",
                  "companyName": "VisionGram"
                }
              }
            }
          }
          JSON

      - name: Install EAS CLI
        run: npm install --global eas-cli

      - name: Install expo-modules-autolinking
        run: npm install --save-dev expo-modules-autolinking

      - name: EAS Build (iOS)
        run: eas build --platform ios --profile production --non-interactive --no-wait

      - name: EAS Submit (iOS)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas submit --platform ios --profile production --non-interactive
