name: ios TestFlight via Expo EAS

on:
  workflow_dispatch:

jobs:
  build-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Expo login (EXPO_TOKEN)
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Write App Store Connect API key JSON
        run: echo "${{ secrets.APP_STORE_CONNECT_API_KEY_JSON }}" > asc_api_key.json

      - name: Install EAS CLI
        run: npm install --global eas-cli

      - name: Prepare ASC API key for eas.json
        run: |
          # Write a temporary Node script to set up the API key values and p8 file
          cat <<'NODE' > set-asc-key.js
          const fs = require('fs');
          // Read the API key JSON
          let asc = {};
          try {
            asc = JSON.parse(fs.readFileSync('asc_api_key.json', 'utf8'));
          } catch (e) {
            asc = {};
          }
          // Write the .p8 file from the key
          if (asc.key) {
            fs.writeFileSync('asc_key.p8', asc.key);
          }
          // Read the existing eas.json or start with empty object
          let eas = {};
          try {
            eas = JSON.parse(fs.readFileSync('eas.json', 'utf8'));
          } catch (e) {
            eas = {};
          }
          if (!eas.submit) eas.submit = {};
          if (!eas.submit.production) eas.submit.production = {};
          if (!eas.submit.production.ios) eas.submit.production.ios = {};
          // Set API key fields from asc
          if (asc.key_id) {
            eas.submit.production.ios.ascApiKeyId = asc.key_id;
          }
          if (asc.issuer_id) {
            eas.submit.production.ios.ascApiKeyIssuerId = asc.issuer_id;
          }
          // Always set path to the generated .p8 file
          eas.submit.production.ios.ascApiKeyPath = './asc_key.p8';
          // Ensure companyName is present
          if (!eas.submit.production.ios.companyName || eas.submit.production.ios.companyName === '') {
            eas.submit.production.ios.companyName = 'VisionGram';
          }
          // Write back updated eas.json
          fs.writeFileSync('eas.json', JSON.stringify(eas, null, 2));
          NODE
          # Run the node script
          node set-asc-key.js

      - name: EAS Build and Submit (ios)
        run: eas build --platform ios --profile production --non-interactive --auto-submit-with-profile production
